apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo
spec:
  project: default
  source:
    path: gitops/applications
    repoURL: ssh://git@github.com/DISIC/DesignGouvOvh.git
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
