apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values-dinum.yaml
    path: gitops/cert-manager
    repoURL: ssh://git@github.com/DISIC/DesignGouvOvh.git
    targetRevision: HEAD
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
