apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values-dinum.yaml
    path: gitops/ingress-nginx
    repoURL: ssh://git@github.com/DISIC/DesignGouvOvh.git
    targetRevision: HEAD
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
