controller:
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  ingressClass: nginx

  kind: DaemonSet

  resources:
    limits:
  ##    cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 90Mi

  service:
    enabled: true
    appProtocol: true
    enableHttp: true
    enableHttps: true
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
    type: LoadBalancer

  metrics:
    enabled: false


