apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: olivier.javaux@ovhcloud.com
    preferredChain: ""
    privateKeySecretRef:
      name: cluster-issuer-staging-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
