apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  db_url: {{ .Values.server.db.db_url | b64enc }}
  db_username: {{ .Values.server.db.db_user | b64enc }}
  db_password: {{ .Values.server.db.db_password | b64enc }}
