apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-applications
  namespace: argo
spec:
  project: default
  source:
    path: applications
    repoURL: ssh://git@gitlab.akkibharath001.tk/administration/helm
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
