name: Docker Images CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        run: |
          if [[ "${{ steps.meta.outputs.tags }}" == "" ]]; then
            echo "TAG=dev" >> $GITHUB_ENV
          else
            echo "TAG=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./docker_images/base
          push: true
          # tags: ${{ steps.meta.outputs.tags }}
          tags: "designgouvovh/base:${{ env.TAG }}"
          labels: ${{ steps.meta.outputs.labels }}

